export type {
  DatasetColumnMapping,
  DatasetDetailSummary,
  DatasetFileCommitRequest,
  DatasetFileField,
  DatasetFileFormat,
  DatasetFileImportPreview,
  DatasetFileInspection,
  DatasetFilePreviewRequest,
  DatasetImportCandle,
  DatasetImportRequest,
  DatasetProvenance,
  DatasetProvenanceKind,
  DatasetSnapshot,
  DatasetSortDirection,
  DatasetSortField,
  DatasetSummary,
  DatasetTimeframe,
  MarketDataCoverageReport,
  MarketDataQualityAcceptance,
  MarketDataQualityIssue,
  MarketDataQualityIssueCode,
  MarketDataQualityReport,
  MarketDataQualityScore,
  MarketType,
  OHLCVCandle,
  TradingPair,
} from '@/features/datasets/api/types';
export type {
  HistoricalDatasetCommitRequest,
  HistoricalDatasetImportPreview,
  HistoricalDatasetImportRequest,
  MarketDataConnection,
  MarketDataConnectionCreateRequest,
  MarketDataConnectionHealth,
  MarketDataConnectionState,
  MarketDataImportOperation,
  MarketDataImportRecord,
  MarketDataImportStatus,
  MarketDataProviderAccessMode,
  MarketDataProviderErrorCode,
  MarketDataProviderSummary,
} from '@/features/connections/api/types';
export type {
  AcceptancePolicy,
  AcceptancePolicyPreset,
  BacktestConfig,
  CreatedResearchExperiment,
  EMACrossoverExecutionParameters,
  ExperimentAcceptanceCheck,
  ExperimentAcceptanceCheckName,
  ExperimentAcceptanceComparison,
  ExperimentAcceptanceOutcome,
  ExperimentAcceptanceResult,
  ExperimentAnalyticsReport,
  ExperimentComparisonEntry,
  ExperimentComparisonMetric,
  ExperimentComparisonRankingDirection,
  ExperimentComparisonRequest,
  ExperimentComparisonResult,
  ExperimentExecution,
  ExperimentExecutionParameters,
  ExperimentExecutionStatus,
  ExperimentParameter,
  ExperimentPerformanceSeries,
  ExperimentPeriodReturn,
  ExperimentReplayCode,
  ExperimentReplayStatus,
  ExperimentReplayVerification,
  ExperimentResearchReport,
  ExperimentSortDirection,
  ExperimentSortField,
  ExperimentSummary,
  ExperimentTradeDistribution,
  HistoricalBenchmarkContext,
  HistoricalDrawdownEpisode,
  HistoricalDrawdownEpisodeStatus,
  HistoricalEquityPoint,
  HistoricalExecutionParameters,
  HistoricalPerformancePoint,
  HistoricalPerformancePointKind,
  HistoricalPerformanceSeries,
  PresetExperimentResearchReport,
  ResearchMetricDefinition,
  ResearchMetricKey,
  RSIThresholdExecutionParameters,
  SMACrossoverExecutionParameters,
  StoredDatasetEMACrossoverExecutionRequest,
  StoredDatasetEMACrossoverRequest,
  StoredDatasetHistoricalExecutionRequest,
  StoredDatasetRSIThresholdExecutionRequest,
  StoredDatasetRSIThresholdRequest,
  StoredDatasetSMACrossoverExecutionRequest,
  StoredDatasetSMACrossoverRequest,
  StoredDatasetStrategyExecutionRequest,
} from '@/features/experiments/api/types';
export type {
  ResearchStrategyMetadata,
  ResearchStrategyName,
  StrategyParameterKind,
  StrategyParameterMetadata,
} from '@/features/strategies/api/types';
export type {
  HistoricalFoldReturnDirection,
  StoredDatasetEMACrossoverWalkForwardExecutionRequest,
  StoredDatasetEMACrossoverWalkForwardRequest,
  StoredDatasetRSIThresholdWalkForwardExecutionRequest,
  StoredDatasetRSIThresholdWalkForwardRequest,
  StoredDatasetSMACrossoverWalkForwardExecutionRequest,
  StoredDatasetSMACrossoverWalkForwardRequest,
  StoredDatasetStrategyWalkForwardExecutionRequest,
  WalkForwardConfig,
  WalkForwardExecution,
  WalkForwardExecutionRequest,
  WalkForwardExecutionStatus,
  WalkForwardFoldStatistics,
  WalkForwardMode,
  WalkForwardRunSortDirection,
  WalkForwardRunSortField,
  WalkForwardRunSummary,
  WalkForwardStabilityReport,
} from '@/features/walk-forward/api/types';
export type {
  CreateOptimizationExecutionRequest,
  OptimizationExecution,
  OptimizationExecutionStatus,
  OptimizationExecutionSubmission,
  OptimizationParameterGrid,
  OptimizationPlan,
  OptimizationRobustnessBreakdown,
  OptimizationRobustnessPlan,
  OptimizationRobustnessRankingEntry,
  OptimizationRobustnessRankingResult,
  OptimizationRobustnessWeights,
  OptimizationTrial,
  OptimizationTrialEvaluation,
  OptimizationTrialRejectionReason,
} from '@/features/optimizations/api/types';
export type {
  ExperimentSignalSortDirection,
  SignalDirection,
  StrategyFeature,
  StrategySignal,
} from '@/features/signals/api/types';
export type {
  CandidateAction,
  CandidateComparisonEntry,
  CandidateComparisonResult,
  CandidateDecisionEvidence,
  CandidateDecisionLineage,
  CandidateDecisionLineageKind,
  CandidateDecisionLineageNode,
  CandidateDecisionLineageStatus,
  CandidateExitReason,
  CandidateJournalOccurrence,
  CandidateOccurrenceType,
  CandidateProjectionDetail,
  CandidateProjectionSummary,
  CandidateRankHistoryEntry,
  CandidateRankingBreakdown,
  CandidateRankingEvidenceComponent,
  CandidateRankingEvidenceComponentName,
  CandidateRankingTieBreakEvidence,
  CandidateReplaySkipReason,
  CandidateReplayStatus,
  CandidateRiskCheck,
  CandidateRiskCheckName,
  CandidateRiskCompatibilityBreakdown,
  CandidateRiskDecision,
  CandidateStatus,
  ResearchCandidateSnapshot,
} from '@/features/candidates/api/types';
export type {
  PortfolioRiskSnapshot,
  RiskBudgetUtilization,
  RiskDashboardReport,
  RiskDecisionEvent,
  RiskDecisionSummary,
  RiskRejectionReasonSummary,
} from '@/features/risk/api/types';
export type {
  PortfolioAnalyticsReport,
  PortfolioTimelineEvent,
  PortfolioTimelineEventType,
  PositionDetailReport,
  PositionLineageStatus,
  SimulatedPortfolio,
  SimulatedPortfolioMode,
  SimulatedPortfolioStatus,
  SimulatedPortfolioSummary,
  SimulatedPosition,
  SimulatedPositionSide,
  SimulatedPositionStatus,
} from '@/features/portfolios/api/types';
export type {
  ResearchActivityItem,
  ResearchActivityType,
  ResearchOverview,
  ResearchStage,
} from '@/features/overview/api/types';
export type {
  BackgroundJobKind,
  BackgroundJobStatus,
  BackgroundJobSummary,
} from '@/features/jobs/api/types';

export interface Page<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
  count: number;
  has_next: boolean;
  has_previous: boolean;
}

export type {
  ArchitectureCandidate,
  ArchitectureRecommendation,
  ConnectionHealthSummary,
  ImportOperationsSummary,
  JobQueueSummary,
  MonitoringOverallStatus,
  MonitoringSummary,
  OperationalFailureReason,
  OperationalJobSummary,
  OperationalMonitoringSummary,
  RecommendationSeverity,
  RecommendationStatus,
  SystemMetricName,
  SystemMetricSample,
} from '@/features/monitoring/api/types';
