import type { DashboardLocale } from '@/components/dashboard/dashboard-copy';

export type SignalsCopy = {
  eyebrow: string;
  title: string;
  description: string;
  historicalOnly: string;
  disclaimer: string;
  total: string;
  loading: string;
  emptyExperimentsTitle: string;
  emptyExperimentsDescription: string;
  emptySignalsTitle: string;
  emptySignalsDescription: string;
  errorTitle: string;
  errorDescription: string;
  retry: string;
  previous: string;
  next: string;
  page: string;
  filters: {
    title: string;
    description: string;
    experiment: string;
    experimentPlaceholder: string;
    direction: string;
    allDirections: string;
    closedFrom: string;
    closedTo: string;
    sortDirection: string;
    apply: string;
    applying: string;
    reset: string;
    ascending: string;
    descending: string;
  };
  fields: {
    score: string;
    strategy: string;
    dataset: string;
    pair: string;
    timeframe: string;
    candleOpen: string;
    candleClose: string;
    generatedAt: string;
    reason: string;
    features: string;
  };
  directions: {
    long: string;
    short: string;
    neutral: string;
  };
};

const copies: Record<DashboardLocale, SignalsCopy> = {
  fa: {
    eyebrow: 'Historical strategy output',
    title: 'سیگنال‌های پژوهشی',
    description:
      'سیگنال‌های تولیدشده در آزمایش‌های تاریخی را همراه با امتیاز، دلیل و Featureهای محاسبه‌شده بررسی کنید.',
    historicalOnly: 'فقط پژوهش تاریخی',
    disclaimer:
      'این داده‌ها خروجی شبیه‌سازی تاریخی هستند و برای اجرای معامله واقعی یا تصمیم مالی طراحی نشده‌اند.',
    total: 'تعداد سیگنال‌ها',
    loading: 'در حال دریافت سیگنال‌ها',
    emptyExperimentsTitle: 'آزمایشی ثبت نشده است',
    emptyExperimentsDescription:
      'برای مشاهده سیگنال‌ها ابتدا باید یک آزمایش پژوهشی ذخیره‌شده وجود داشته باشد.',
    emptySignalsTitle: 'سیگنالی پیدا نشد',
    emptySignalsDescription: 'آزمایش انتخاب‌شده با فیلترهای فعلی سیگنال تاریخی ندارد.',
    errorTitle: 'دریافت سیگنال‌ها ناموفق بود',
    errorDescription: 'اتصال Backend، آزمایش و فیلترهای انتخاب‌شده را بررسی کنید.',
    retry: 'تلاش مجدد',
    previous: 'قبلی',
    next: 'بعدی',
    page: 'صفحه',
    filters: {
      title: 'انتخاب آزمایش و فیلترها',
      description:
        'سیگنال‌های یک آزمایش را بر اساس جهت، زمان بسته‌شدن کندل و ترتیب زمانی محدود کنید.',
      experiment: 'آزمایش',
      experimentPlaceholder: 'یک آزمایش انتخاب کنید',
      direction: 'جهت سیگنال',
      allDirections: 'همه جهت‌ها',
      closedFrom: 'بسته‌شدن کندل از',
      closedTo: 'بسته‌شدن کندل تا',
      sortDirection: 'ترتیب زمانی',
      apply: 'نمایش سیگنال‌ها',
      applying: 'در حال دریافت',
      reset: 'پاک‌کردن فیلترها',
      ascending: 'قدیمی‌ترین ابتدا',
      descending: 'جدیدترین ابتدا',
    },
    fields: {
      score: 'امتیاز پژوهشی',
      strategy: 'Strategy',
      dataset: 'Dataset',
      pair: 'جفت بازار',
      timeframe: 'تایم‌فریم',
      candleOpen: 'شروع کندل',
      candleClose: 'پایان کندل',
      generatedAt: 'زمان تولید',
      reason: 'دلیل تولید سیگنال',
      features: 'Featureهای استفاده‌شده',
    },
    directions: {
      long: 'صعودی پژوهشی',
      short: 'نزولی پژوهشی',
      neutral: 'خنثی',
    },
  },
  en: {
    eyebrow: 'Historical strategy output',
    title: 'Research signals',
    description:
      'Review signals generated by historical experiments together with their scores, reasons, and calculated features.',
    historicalOnly: 'Historical research only',
    disclaimer:
      'These records are historical simulation outputs and are not designed for live execution or financial decisions.',
    total: 'Signals',
    loading: 'Loading signals',
    emptyExperimentsTitle: 'No experiments recorded',
    emptyExperimentsDescription:
      'A stored research experiment is required before historical signals can be displayed.',
    emptySignalsTitle: 'No signals found',
    emptySignalsDescription:
      'The selected experiment has no historical signals matching the current filters.',
    errorTitle: 'Unable to retrieve signals',
    errorDescription: 'Check the backend connection, experiment, and selected filters.',
    retry: 'Try again',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    filters: {
      title: 'Experiment and filters',
      description:
        'Filter signals from one experiment by direction, candle close time, and chronological order.',
      experiment: 'Experiment',
      experimentPlaceholder: 'Select an experiment',
      direction: 'Signal direction',
      allDirections: 'All directions',
      closedFrom: 'Candle closed from',
      closedTo: 'Candle closed to',
      sortDirection: 'Chronological order',
      apply: 'Show signals',
      applying: 'Loading',
      reset: 'Reset filters',
      ascending: 'Oldest first',
      descending: 'Newest first',
    },
    fields: {
      score: 'Research score',
      strategy: 'Strategy',
      dataset: 'Dataset',
      pair: 'Market pair',
      timeframe: 'Timeframe',
      candleOpen: 'Candle opened',
      candleClose: 'Candle closed',
      generatedAt: 'Generated at',
      reason: 'Signal reason',
      features: 'Calculated features',
    },
    directions: {
      long: 'Historical upward signal',
      short: 'Historical downward signal',
      neutral: 'Neutral',
    },
  },
};

export function getSignalsCopy(locale: DashboardLocale): SignalsCopy {
  return copies[locale];
}
