import type { DashboardLocale } from '@/components/dashboard/dashboard-copy';

const copies = {
  en: {
    eyebrow: 'Historical walk-forward execution',
    title: 'Run historical strategy walk-forward analysis',
    description:
      'Configure chronological train and test windows for a stored historical dataset. This operation never places real orders.',
    historicalOnly: 'Historical research only',
    fields: {
      dataset: 'Dataset',
      datasetPlaceholder: 'Select a historical dataset',
      strategy: 'Strategy',
      mode: 'Window mode',
      fastPeriod: 'Fast EMA period',
      slowPeriod: 'Slow EMA period',
      rsiPeriod: 'RSI period',
      oversoldThreshold: 'Oversold threshold',
      overboughtThreshold: 'Overbought threshold',
      horizonCandles: 'Evaluation horizon',
      trainCandles: 'Train candles',
      testCandles: 'Test candles',
      stepCandles: 'Step candles',
      gapCandles: 'Gap candles',
      startingBalance: 'Starting balance',
      allocationFraction: 'Allocation fraction',
      feeRate: 'Fee rate',
      slippageRate: 'Slippage rate',
    },
    strategy: {
      emaCrossover: 'EMA crossover',
      rsiThreshold: 'RSI threshold',
    },
    modes: {
      rolling: 'Rolling',
      expanding: 'Expanding',
    },
    estimate: {
      title: 'Estimated execution',
      candles: 'Dataset candles',
      folds: 'Estimated folds',
      unavailable: 'Select valid windows to calculate folds.',
    },
    actions: {
      run: 'Queue historical walk-forward',
      queuing: 'Queuing walk-forward...',
      running: 'Running walk-forward...',
      retryDatasets: 'Retry loading datasets',
      viewResult: 'View stability report',
    },
    states: {
      loadingDatasets: 'Loading historical datasets...',
      noDatasets: 'No historical dataset is available. Import a dataset first.',
      datasetLoadError: 'Historical datasets could not be loaded.',
      queued: 'The walk-forward execution is waiting to start.',
      running: 'Historical folds are being processed.',
      progress: 'Fold progress',
      foldsCompleted: 'Completed folds',
      success: 'The walk-forward stability report was created successfully.',
    },
    errors: {
      datasetRequired: 'Select a historical dataset.',
      invalidFastPeriod: 'Fast EMA period must be an integer greater than or equal to 2.',
      invalidSlowPeriod: 'Slow EMA period must be an integer greater than or equal to 3.',
      slowMustBeGreater: 'Slow EMA period must be greater than the fast EMA period.',
      invalidRsiPeriod: 'RSI period must be an integer greater than or equal to 2.',
      invalidOversoldThreshold: 'Oversold threshold must be greater than 0 and less than 50.',
      invalidOverboughtThreshold: 'Overbought threshold must be greater than 50 and less than 100.',
      invalidHorizon: 'Evaluation horizon must be a positive integer.',
      invalidTrain: 'Train candles must be an integer greater than or equal to 2.',
      invalidTest: 'Test candles must be a positive integer.',
      invalidStep: 'Step candles must be a positive integer.',
      stepBeforeTest: 'Step candles must be greater than or equal to test candles.',
      invalidGap: 'Gap candles must be an integer greater than or equal to zero.',
      invalidStartingBalance: 'Starting balance must be greater than zero.',
      invalidAllocation: 'Allocation fraction must be greater than 0 and at most 1.',
      invalidFee: 'Fee rate must be greater than or equal to 0 and less than 1.',
      invalidSlippage: 'Slippage rate must be greater than or equal to 0 and less than 1.',
      insufficientCandles:
        'The selected dataset does not contain enough candles for one complete fold.',
      datasetNotFound: 'The selected dataset no longer exists.',
      validationFailed: 'The walk-forward parameters or dataset were rejected.',
      generic: 'The historical walk-forward execution could not be queued. Please try again.',
      executionFailed:
        'The historical walk-forward execution failed. Review the parameters and try again.',
      statusUnavailable: 'The walk-forward status could not be refreshed. Please try again.',
      missingResult: 'The execution completed without a stability report identifier.',
    },
  },
  fa: {
    eyebrow: 'اجرای تاریخی Walk-forward',
    title: 'اجرای تحلیل تاریخی Walk-forward استراتژی',
    description:
      'پنجره‌های زمانی Train و Test را برای یک دیتاست تاریخی تنظیم کنید. این عملیات هیچ سفارش واقعی ثبت نمی‌کند.',
    historicalOnly: 'فقط پژوهش تاریخی',
    fields: {
      dataset: 'دیتاست',
      datasetPlaceholder: 'یک دیتاست تاریخی انتخاب کنید',
      strategy: 'استراتژی',
      mode: 'نوع پنجره',
      fastPeriod: 'دوره EMA سریع',
      slowPeriod: 'دوره EMA آهسته',
      rsiPeriod: 'دوره RSI',
      oversoldThreshold: 'آستانه اشباع فروش',
      overboughtThreshold: 'آستانه اشباع خرید',
      horizonCandles: 'افق ارزیابی',
      trainCandles: 'کندل‌های Train',
      testCandles: 'کندل‌های Test',
      stepCandles: 'فاصله حرکت',
      gapCandles: 'فاصله Train و Test',
      startingBalance: 'موجودی اولیه شبیه‌سازی',
      allocationFraction: 'سهم تخصیص',
      feeRate: 'نرخ کارمزد شبیه‌سازی',
      slippageRate: 'نرخ لغزش قیمت شبیه‌سازی',
    },
    strategy: {
      emaCrossover: 'تقاطع EMA',
      rsiThreshold: 'آستانه RSI',
    },
    modes: {
      rolling: 'غلتان',
      expanding: 'گسترش‌یابنده',
    },
    estimate: {
      title: 'برآورد اجرا',
      candles: 'کندل‌های دیتاست',
      folds: 'تعداد Fold پیش‌بینی‌شده',
      unavailable: 'برای محاسبه Fold، پنجره‌های معتبر وارد کنید.',
    },
    actions: {
      run: 'افزودن Walk-forward تاریخی به صف',
      queuing: 'در حال افزودن Walk-forward به صف...',
      running: 'در حال اجرای Walk-forward...',
      retryDatasets: 'تلاش مجدد برای دریافت دیتاست‌ها',
      viewResult: 'مشاهده گزارش پایداری',
    },
    states: {
      loadingDatasets: 'در حال دریافت دیتاست‌های تاریخی...',
      noDatasets: 'هنوز دیتاست تاریخی ثبت نشده است. ابتدا یک دیتاست وارد کنید.',
      datasetLoadError: 'دریافت دیتاست‌های تاریخی امکان‌پذیر نبود.',
      queued: 'اجرای Walk-forward در صف قرار گرفته است.',
      running: 'Foldهای تاریخی در حال پردازش هستند.',
      progress: 'پیشرفت Foldها',
      foldsCompleted: 'Foldهای تکمیل‌شده',
      success: 'گزارش پایداری Walk-forward با موفقیت ایجاد شد.',
    },
    errors: {
      datasetRequired: 'یک دیتاست تاریخی انتخاب کنید.',
      invalidFastPeriod: 'دوره EMA سریع باید عدد صحیح و حداقل ۲ باشد.',
      invalidSlowPeriod: 'دوره EMA آهسته باید عدد صحیح و حداقل ۳ باشد.',
      slowMustBeGreater: 'دوره EMA آهسته باید از دوره EMA سریع بزرگ‌تر باشد.',
      invalidRsiPeriod: 'دوره RSI باید عدد صحیح و حداقل ۲ باشد.',
      invalidOversoldThreshold: 'آستانه اشباع فروش باید بزرگ‌تر از صفر و کوچک‌تر از ۵۰ باشد.',
      invalidOverboughtThreshold: 'آستانه اشباع خرید باید بزرگ‌تر از ۵۰ و کوچک‌تر از ۱۰۰ باشد.',
      invalidHorizon: 'افق ارزیابی باید یک عدد صحیح مثبت باشد.',
      invalidTrain: 'تعداد کندل Train باید عدد صحیح و حداقل ۲ باشد.',
      invalidTest: 'تعداد کندل Test باید یک عدد صحیح مثبت باشد.',
      invalidStep: 'فاصله حرکت باید یک عدد صحیح مثبت باشد.',
      stepBeforeTest: 'فاصله حرکت باید حداقل برابر تعداد کندل Test باشد.',
      invalidGap: 'فاصله Train و Test باید یک عدد صحیح و حداقل صفر باشد.',
      invalidStartingBalance: 'موجودی اولیه باید بزرگ‌تر از صفر باشد.',
      invalidAllocation: 'سهم تخصیص باید بزرگ‌تر از صفر و حداکثر برابر ۱ باشد.',
      invalidFee: 'نرخ کارمزد باید حداقل صفر و کوچک‌تر از ۱ باشد.',
      invalidSlippage: 'نرخ لغزش قیمت باید حداقل صفر و کوچک‌تر از ۱ باشد.',
      insufficientCandles: 'تعداد کندل‌های دیتاست برای ساخت یک Fold کامل کافی نیست.',
      datasetNotFound: 'دیتاست انتخاب‌شده دیگر وجود ندارد.',
      validationFailed: 'پارامترها یا دیتاست توسط Backend رد شدند.',
      generic: 'اجرای Walk-forward تاریخی وارد صف نشد. دوباره تلاش کنید.',
      executionFailed:
        'اجرای Walk-forward تاریخی ناموفق بود. پارامترها را بررسی و دوباره تلاش کنید.',
      statusUnavailable: 'دریافت وضعیت Walk-forward امکان‌پذیر نبود. دوباره تلاش کنید.',
      missingResult: 'اجرا کامل شد اما شناسه گزارش پایداری دریافت نشد.',
    },
  },
} as const;

export function getWalkForwardRunCopy(locale: DashboardLocale) {
  return copies[locale];
}
