from trd_bot.main import create_app

FRONTEND_API_OPERATIONS = {
    ("GET", "/api/v1/health"),
    ("GET", "/api/v1/market-data/providers"),
    ("GET", "/api/v1/market-data/connections"),
    ("POST", "/api/v1/market-data/connections"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/test"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/enable"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/disable"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/datasets/preview"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/datasets"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/dataset-jobs"),
    ("GET", "/api/v1/market-data/connections/{connection_id}/imports"),
    ("GET", "/api/v1/market-data/connections/{connection_id}/imports/{import_id}"),
    ("GET", "/api/v1/market-data/connections/{connection_id}/imports/{import_id}/versions"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/imports/{import_id}/refresh"),
    ("POST", "/api/v1/market-data/connections/{connection_id}/imports/{import_id}/refresh-job"),
    ("GET", "/api/v1/research/datasets"),
    ("POST", "/api/v1/research/datasets"),
    ("POST", "/api/v1/research/datasets/files/inspect"),
    ("POST", "/api/v1/research/datasets/files/preview"),
    ("POST", "/api/v1/research/datasets/files"),
    ("GET", "/api/v1/research/datasets/{dataset_id}/summary"),
    ("GET", "/api/v1/research/datasets/{dataset_id}/candles"),
    ("GET", "/api/v1/research/datasets/{dataset_id}"),
    ("GET", "/api/v1/research/overview"),
    ("GET", "/api/v1/research/overview/activity"),
    ("GET", "/api/v1/research/strategies"),
    ("GET", "/api/v1/research/strategies/{strategy_name}/versions"),
    ("GET", "/api/v1/research/strategies/{strategy_name}/versions/{version}"),
    ("POST", "/api/v1/research/experiment-executions"),
    ("GET", "/api/v1/research/experiment-executions/{execution_id}"),
    ("POST", "/api/v1/research/experiments/ema-crossover/from-dataset"),
    ("GET", "/api/v1/research/experiments"),
    ("POST", "/api/v1/research/experiments/compare"),
    ("GET", "/api/v1/research/experiments/{experiment_id}/summary"),
    ("POST", "/api/v1/research/experiments/{experiment_id}/replay-verification"),
    ("GET", "/api/v1/research/experiments/{experiment_id}/performance-series"),
    ("GET", "/api/v1/research/experiments/{experiment_id}/analytics"),
    ("GET", "/api/v1/research/acceptance-policies"),
    ("POST", "/api/v1/research/experiments/{experiment_id}/report/presets/{preset_id}"),
    ("GET", "/api/v1/research/experiments/{experiment_id}/report/presets/{preset_id}/export.csv"),
    ("GET", "/api/v1/research/experiments/{experiment_id}/signals"),
    ("GET", "/api/v1/research/experiments/{experiment_id}/signals/{signal_id}"),
    ("POST", "/api/v1/research/walk-forward-executions"),
    ("GET", "/api/v1/research/walk-forward-executions/{execution_id}"),
    ("GET", "/api/v1/research/walk-forward/runs"),
    ("GET", "/api/v1/research/walk-forward/runs/{execution_id}/summary"),
    ("GET", "/api/v1/research/walk-forward/runs/{execution_id}/stability"),
    ("POST", "/api/v1/research/optimization-executions"),
    ("GET", "/api/v1/research/optimization-executions"),
    ("GET", "/api/v1/research/optimization-executions/{execution_id}"),
    ("GET", "/api/v1/research/candidates"),
    ("POST", "/api/v1/research/candidates/compare"),
    ("GET", "/api/v1/research/candidates/{candidate_id}"),
    ("GET", "/api/v1/research/candidates/{candidate_id}/lineage"),
    ("GET", "/api/v1/research/risk"),
    ("GET", "/api/v1/research/portfolios"),
    ("GET", "/api/v1/research/portfolios/{portfolio_id}"),
    ("GET", "/api/v1/research/portfolios/{portfolio_id}/analytics"),
    ("GET", "/api/v1/research/portfolios/{portfolio_id}/positions"),
    ("GET", "/api/v1/research/portfolios/{portfolio_id}/positions/{position_id}"),
    ("GET", "/api/v1/research/portfolios/{portfolio_id}/positions/{position_id}/detail"),
    ("GET", "/api/v1/research/portfolios/{portfolio_id}/timeline"),
    ("GET", "/api/v1/jobs/{job_id}"),
    ("GET", "/api/v1/monitoring/summary"),
}


def test_backend_openapi_preserves_every_frontend_consumed_operation() -> None:
    paths = create_app().openapi()["paths"]
    backend_operations = {
        (method.upper(), path) for path, operations in paths.items() for method in operations
    }

    assert backend_operations >= FRONTEND_API_OPERATIONS
