import type { PlatformLocale } from '@/platform/i18n';

const copies = {
  en: {
    eyebrow: 'Bounded historical optimization',
    title: 'Strategy optimizations',
    description:
      'Queue bounded parameter searches and rank every completed trial with out-of-sample walk-forward evidence.',
    historicalOnly: 'Historical research only',
    total: 'Executions',
    loading: 'Loading optimization executions',
    errorTitle: 'Optimization executions could not be loaded',
    errorDescription: 'Check the Backend connection and try again.',
    retry: 'Retry',
    emptyTitle: 'No optimization execution yet',
    emptyDescription: 'Configure the first bounded parameter grid above.',
    viewDetails: 'View robustness ranking',
    pagination: 'Optimization execution pages',
    previous: 'Previous',
    next: 'Next',
    statuses: {
      queued: 'Queued',
      running: 'Running',
      succeeded: 'Succeeded',
      failed: 'Failed',
    },
    objectives: {
      excess_return: 'Excess return',
      total_return: 'Total return',
      max_drawdown_fraction: 'Maximum drawdown',
    },
    modes: {
      rolling: 'Rolling',
      expanding: 'Expanding',
    },
    fields: {
      createdAt: 'Created',
      objective: 'Objective',
      progress: 'Trial progress',
      folds: 'Folds per trial',
      bestExperiment: 'Best experiment',
      notAvailable: 'Not available',
    },
    form: {
      title: 'Queue an optimization',
      description:
        'Values in each parameter grid are combined deterministically, then validated out of sample.',
      parameterGrid: 'Parameter grid',
      parameterHint: 'Comma-separated values; at most 20 values per parameter.',
      objective: 'Ranking objective',
      estimateTitle: 'Bounded workload estimate',
      requested: 'Requested combinations',
      valid: 'Valid trials',
      skipped: 'Skipped combinations',
      folds: 'Folds per trial',
      validationRuns: 'Trial-fold runs',
      unavailable: 'Select a dataset and enter valid grids and windows to estimate the workload.',
      queue: 'Queue optimization',
      queuing: 'Queuing optimization...',
      running: 'Running optimization...',
      queuedState: 'The durable optimization job is waiting to start.',
      runningState: 'Trials and walk-forward folds are being evaluated.',
      progress: 'Completed trials',
      errors: {
        gridRequired: 'Enter at least one value for every strategy parameter.',
        gridInvalid: 'Every grid value must satisfy the strategy parameter bounds.',
        gridDuplicate: 'Parameter grids cannot contain duplicate values.',
        tooManyValues: 'A parameter grid can contain at most 20 values.',
        tooManyTrials: 'The parameter grid can request at most 100 combinations.',
        noValidTrials: 'The parameter grid contains no valid strategy combination.',
        foldRange: 'Optimization requires between 3 and 12 walk-forward folds.',
        tooManyValidationRuns: 'The workload can contain at most 300 trial-fold runs.',
        datasetNotFound: 'The selected dataset no longer exists.',
        validationFailed: 'The Backend rejected the optimization plan or robustness workload.',
        generic: 'The optimization could not be queued. Please try again.',
        executionFailed: 'The optimization execution failed.',
        statusUnavailable: 'The optimization status could not be refreshed.',
      },
    },
    detail: {
      back: 'Back to optimizations',
      notFoundTitle: 'Optimization execution not found',
      notFoundDescription: 'The execution ID does not exist or is no longer available.',
      eyebrow: 'Optimization execution',
      disclaimer:
        'All scores describe historical simulations. They are not forecasts or trading recommendations.',
      summary: 'Execution summary',
      summaryDescription: 'Durable lifecycle state and bounded workload.',
      plan: 'Parameter plan',
      planDescription: 'Canonical parameter combinations accepted by the strategy registry.',
      ranking: 'Out-of-sample robustness ranking',
      rankingDescription:
        'Eligible trials ranked by a versioned score that rewards out-of-sample evidence and penalizes instability.',
      noRanking: 'A final robustness ranking is not available for this execution.',
      rejected: 'Rejected trial evidence',
      rejectedDescription: 'Trials excluded from ranking by the fail-closed eligibility policy.',
      noRejected: 'No completed trial was rejected by the robustness policy.',
      configuration: 'Execution configuration',
      configurationDescription: 'Reproducible backtest and walk-forward inputs.',
      planTableScroll: 'Parameter plan table; scroll horizontally to view all columns',
      rankingTableScroll:
        'Out-of-sample robustness ranking table; scroll horizontally to view all columns',
      rejectedTableScroll: 'Rejected trial evidence table; scroll horizontally to view all columns',
      fields: {
        executionId: 'Execution ID',
        datasetId: 'Dataset ID',
        strategy: 'Strategy',
        version: 'Version',
        status: 'Status',
        createdAt: 'Created',
        finishedAt: 'Finished',
        objective: 'Objective',
        requested: 'Requested',
        skipped: 'Skipped',
        totalTrials: 'Valid trials',
        completedTrials: 'Completed trials',
        evaluatedTrials: 'Evaluated trials',
        eligibleTrials: 'Eligible trials',
        rejectedTrials: 'Rejected trials',
        totalFolds: 'Folds per trial',
        validationRuns: 'Trial-fold runs',
        scoreVersion: 'Score version',
        trial: 'Trial',
        parameters: 'Parameters',
        score: 'Robustness score',
        inSample: 'In-sample objective',
        outOfSample: 'Out-of-sample objective',
        medianExcess: 'Median excess return',
        positiveFolds: 'Positive folds',
        tradedFolds: 'Traded folds',
        dispersion: 'Return dispersion',
        drawdown: 'Worst drawdown',
        gap: 'Generalization gap',
        evidence: 'Evidence',
        reason: 'Rejection reason',
        horizon: 'Evaluation horizon',
        mode: 'Window mode',
        trainCandles: 'Train candles',
        testCandles: 'Test candles',
        stepCandles: 'Step candles',
        gapCandles: 'Gap candles',
        startingBalance: 'Starting balance',
        allocationFraction: 'Allocation fraction',
        feeRate: 'Fee rate',
        slippageRate: 'Slippage rate',
      },
      rejectionReasons: {
        insufficient_traded_folds: 'Insufficient traded folds',
      },
    },
  },
  fa: {
    eyebrow: 'بهینه‌سازی تاریخی محدود',
    title: 'بهینه‌سازی استراتژی‌ها',
    description:
      'جست‌وجوی محدود پارامترها را در صف قرار دهید و هر Trial تکمیل‌شده را با شواهد خارج از نمونه Walk-forward رتبه‌بندی کنید.',
    historicalOnly: 'فقط پژوهش تاریخی',
    total: 'اجراها',
    loading: 'در حال دریافت اجراهای بهینه‌سازی',
    errorTitle: 'دریافت اجراهای بهینه‌سازی ناموفق بود',
    errorDescription: 'اتصال Backend را بررسی و دوباره تلاش کنید.',
    retry: 'تلاش مجدد',
    emptyTitle: 'هنوز بهینه‌سازی اجرا نشده است',
    emptyDescription: 'اولین شبکه پارامتر محدود را در بالا تنظیم کنید.',
    viewDetails: 'مشاهده رتبه‌بندی پایداری',
    pagination: 'صفحه‌های اجرای بهینه‌سازی',
    previous: 'قبلی',
    next: 'بعدی',
    statuses: {
      queued: 'در صف',
      running: 'در حال اجرا',
      succeeded: 'موفق',
      failed: 'ناموفق',
    },
    objectives: {
      excess_return: 'بازده مازاد',
      total_return: 'بازده کل',
      max_drawdown_fraction: 'حداکثر افت سرمایه',
    },
    modes: {
      rolling: 'غلتان',
      expanding: 'گسترش‌یابنده',
    },
    fields: {
      createdAt: 'زمان ایجاد',
      objective: 'هدف',
      progress: 'پیشرفت Trialها',
      folds: 'Fold برای هر Trial',
      bestExperiment: 'بهترین آزمایش',
      notAvailable: 'در دسترس نیست',
    },
    form: {
      title: 'افزودن بهینه‌سازی به صف',
      description:
        'مقادیر هر شبکه پارامتر به‌شکل قطعی ترکیب و سپس خارج از نمونه اعتبارسنجی می‌شوند.',
      parameterGrid: 'شبکه پارامتر',
      parameterHint: 'مقادیر جداشده با ویرگول؛ حداکثر ۲۰ مقدار برای هر پارامتر.',
      objective: 'هدف رتبه‌بندی',
      estimateTitle: 'برآورد بار کاری محدود',
      requested: 'ترکیب‌های درخواستی',
      valid: 'Trialهای معتبر',
      skipped: 'ترکیب‌های ردشده',
      folds: 'Fold برای هر Trial',
      validationRuns: 'اجرای Trial-Fold',
      unavailable: 'برای برآورد بار کاری، دیتاست و شبکه‌ها و پنجره‌های معتبر انتخاب کنید.',
      queue: 'افزودن بهینه‌سازی به صف',
      queuing: 'در حال افزودن به صف...',
      running: 'در حال اجرای بهینه‌سازی...',
      queuedState: 'Job پایدار بهینه‌سازی منتظر شروع است.',
      runningState: 'Trialها و Foldهای Walk-forward در حال ارزیابی هستند.',
      progress: 'Trialهای تکمیل‌شده',
      errors: {
        gridRequired: 'برای هر پارامتر استراتژی حداقل یک مقدار وارد کنید.',
        gridInvalid: 'همه مقادیر شبکه باید با محدودیت پارامتر استراتژی سازگار باشند.',
        gridDuplicate: 'شبکه پارامتر نباید مقدار تکراری داشته باشد.',
        tooManyValues: 'هر شبکه پارامتر حداکثر می‌تواند ۲۰ مقدار داشته باشد.',
        tooManyTrials: 'شبکه پارامتر حداکثر می‌تواند ۱۰۰ ترکیب درخواست کند.',
        noValidTrials: 'شبکه پارامتر هیچ ترکیب معتبر استراتژی ندارد.',
        foldRange: 'بهینه‌سازی به ۳ تا ۱۲ Fold از نوع Walk-forward نیاز دارد.',
        tooManyValidationRuns: 'بار کاری حداکثر می‌تواند ۳۰۰ اجرای Trial-Fold داشته باشد.',
        datasetNotFound: 'دیتاست انتخاب‌شده دیگر وجود ندارد.',
        validationFailed: 'برنامه بهینه‌سازی یا بار کاری پایداری توسط Backend رد شد.',
        generic: 'بهینه‌سازی وارد صف نشد. دوباره تلاش کنید.',
        executionFailed: 'اجرای بهینه‌سازی ناموفق بود.',
        statusUnavailable: 'دریافت وضعیت بهینه‌سازی امکان‌پذیر نبود.',
      },
    },
    detail: {
      back: 'بازگشت به بهینه‌سازی‌ها',
      notFoundTitle: 'اجرای بهینه‌سازی پیدا نشد',
      notFoundDescription: 'شناسه اجرا وجود ندارد یا دیگر در دسترس نیست.',
      eyebrow: 'اجرای بهینه‌سازی',
      disclaimer: 'همه امتیازها توصیف شبیه‌سازی تاریخی‌اند و پیش‌بینی یا توصیه معاملاتی نیستند.',
      summary: 'خلاصه اجرا',
      summaryDescription: 'وضعیت چرخه پایدار و بار کاری محدود.',
      plan: 'برنامه پارامترها',
      planDescription: 'ترکیب‌های استاندارد پارامتر پذیرفته‌شده توسط رجیستری استراتژی.',
      ranking: 'رتبه‌بندی پایداری خارج از نمونه',
      rankingDescription:
        'رتبه‌بندی Trialهای واجد شرایط با امتیاز نسخه‌دار مبتنی بر شواهد خارج از نمونه و جریمه ناپایداری.',
      noRanking: 'رتبه‌بندی نهایی پایداری برای این اجرا موجود نیست.',
      rejected: 'شواهد Trialهای ردشده',
      rejectedDescription: 'Trialهای حذف‌شده از رتبه‌بندی بر اساس سیاست fail-closed.',
      noRejected: 'هیچ Trial تکمیل‌شده‌ای توسط سیاست پایداری رد نشده است.',
      configuration: 'پیکربندی اجرا',
      configurationDescription: 'ورودی‌های قابل بازتولید Backtest و Walk-forward.',
      planTableScroll: 'جدول برنامه پارامترها؛ برای مشاهده همه ستون‌ها به‌صورت افقی پیمایش کنید',
      rankingTableScroll:
        'جدول رتبه‌بندی پایداری خارج از نمونه؛ برای مشاهده همه ستون‌ها به‌صورت افقی پیمایش کنید',
      rejectedTableScroll:
        'جدول شواهد Trialهای ردشده؛ برای مشاهده همه ستون‌ها به‌صورت افقی پیمایش کنید',
      fields: {
        executionId: 'شناسه اجرا',
        datasetId: 'شناسه دیتاست',
        strategy: 'استراتژی',
        version: 'نسخه',
        status: 'وضعیت',
        createdAt: 'زمان ایجاد',
        finishedAt: 'زمان پایان',
        objective: 'هدف',
        requested: 'درخواستی',
        skipped: 'ردشده',
        totalTrials: 'Trial معتبر',
        completedTrials: 'Trial تکمیل‌شده',
        evaluatedTrials: 'Trial ارزیابی‌شده',
        eligibleTrials: 'Trial واجد شرایط',
        rejectedTrials: 'Trial ردشده',
        totalFolds: 'Fold برای هر Trial',
        validationRuns: 'اجرای Trial-Fold',
        scoreVersion: 'نسخه امتیاز',
        trial: 'Trial',
        parameters: 'پارامترها',
        score: 'امتیاز پایداری',
        inSample: 'هدف درون نمونه',
        outOfSample: 'هدف خارج از نمونه',
        medianExcess: 'میانه بازده مازاد',
        positiveFolds: 'Foldهای مثبت',
        tradedFolds: 'Foldهای معامله‌دار',
        dispersion: 'پراکندگی بازده',
        drawdown: 'بدترین افت سرمایه',
        gap: 'شکاف تعمیم',
        evidence: 'شواهد',
        reason: 'دلیل رد',
        horizon: 'افق ارزیابی',
        mode: 'نوع پنجره',
        trainCandles: 'کندل‌های Train',
        testCandles: 'کندل‌های Test',
        stepCandles: 'فاصله حرکت',
        gapCandles: 'فاصله Train و Test',
        startingBalance: 'موجودی اولیه',
        allocationFraction: 'سهم تخصیص',
        feeRate: 'نرخ کارمزد',
        slippageRate: 'نرخ لغزش',
      },
      rejectionReasons: {
        insufficient_traded_folds: 'Fold معامله‌دار ناکافی',
      },
    },
  },
} as const;

export function getOptimizationCopy(locale: PlatformLocale) {
  return copies[locale];
}
