export const portfolioAnalyticsCopy = {
  en: {
    title: 'Portfolio performance',
    description:
      'Read-only historical simulation. Equity uses recorded marks after paid fees; no live prices or assumed exit fees.',
    accounting:
      'Net PnL = closed net PnL + open gross unrealized PnL − open entry fees. Trade statistics use closed positions only, after both entry and exit fees.',
    timing:
      'As of the last stored event, not the current clock. Drawdown duration starts at the last equity high and ends at recovery or the last event. Charts are stepwise between observed events.',
    noTrades: 'No closed trades: win rate, expectancy and average hold time are unavailable.',
    noLosses: 'Profit factor is unavailable because there are no losing closed trades.',
    unavailable: 'Unavailable',
    asOf: 'Snapshot time (UTC)',
    starting_equity: 'Starting equity',
    ending_equity: 'Ending equity',
    net_pnl: 'Net PnL',
    return_fraction: 'Total return',
    fees_paid: 'Paid fees',
    closed_net_pnl: 'Closed net PnL',
    open_gross_unrealized_pnl: 'Open gross unrealized PnL',
    open_entry_fees: 'Open entry fees',
    open_net_pnl: 'Open net PnL',
    closed_count: 'Closed positions',
    open_count: 'Open positions',
    winning_count: 'Wins after fees',
    losing_count: 'Losses after fees',
    breakeven_count: 'Breakeven after fees',
    win_rate: 'Win rate',
    profit_factor: 'Profit factor',
    expectancy: 'Expectancy per closed trade',
    average_hold_seconds: 'Average closed hold time (seconds)',
    duration_seconds: 'Observed duration (seconds)',
    max_drawdown_fraction: 'Maximum drawdown',
    max_drawdown_duration_seconds: 'Longest drawdown (seconds)',
    current_drawdown_duration_seconds: 'Current drawdown duration (seconds)',
    open_exposure: 'Gross marked open exposure',
    exposure_fraction: 'Exposure / equity',
    exposureNote: 'Exposure = sum of open quantity × last stored price, for both long and short.',
    equity: 'Recorded equity',
    drawdown: 'Recorded drawdown',
    returns: 'Recorded return',
    chartMetricSelector: 'Select a portfolio chart metric on mobile',
    pair: 'Trading pair',
    pairs: 'Trades by pair',
    exits: 'Exit reasons (closed positions)',
    count: 'Count',
    evidence: 'Event values used by the charts',
    sequence: 'Sequence',
    empty: 'No positions recorded',
    exitNote: 'Missing or conflicting journal evidence is classified as unknown, never inferred.',
    reasons: {
      unknown: 'Unknown',
      invalidation: 'Invalidation',
      target: 'Target',
      trend_reversal: 'Trend reversal',
      portfolio_risk: 'Portfolio risk',
      data_unreliable: 'Unreliable data',
      time_expiry: 'Time expiry',
      end_of_data: 'End of data',
    },
  },
  fa: {
    title: 'تحلیل عملکرد پرتفوی',
    description:
      'شبیه‌سازی تاریخی و فقط‌خواندنی. ارزش پرتفوی بر اساس قیمت‌های ثبت‌شده پس از کارمزد پرداختی است؛ بدون قیمت زنده یا کارمزد خروج فرضی.',
    accounting:
      'سود خالص = سود خالص معاملات بسته + سود ناخالص محقق‌نشده باز − کارمزد ورود موقعیت باز. آمار معاملات فقط از موقعیت‌های بسته و پس از کارمزد ورود و خروج محاسبه می‌شود.',
    timing:
      'مبنا آخرین رویداد ذخیره‌شده است، نه ساعت فعلی. مدت افت از آخرین سقف ارزش تا بازیابی یا آخرین رویداد است. نمودارها بین مشاهدات به‌صورت پله‌ای نمایش داده می‌شوند.',
    noTrades: 'معامله بسته‌ای وجود ندارد؛ نرخ برد، امید ریاضی و میانگین نگهداری ناموجودند.',
    noLosses: 'به دلیل نبود معامله بسته زیان‌ده، ضریب سود تعریف نشده است.',
    unavailable: 'ناموجود',
    asOf: 'زمان اسنپ‌شات (UTC)',
    starting_equity: 'ارزش آغازین',
    ending_equity: 'ارزش پایانی',
    net_pnl: 'سود و زیان خالص',
    return_fraction: 'بازده کل',
    fees_paid: 'کارمزد پرداختی',
    closed_net_pnl: 'سود خالص معاملات بسته',
    open_gross_unrealized_pnl: 'سود ناخالص محقق‌نشده باز',
    open_entry_fees: 'کارمزد ورود موقعیت باز',
    open_net_pnl: 'سود خالص موقعیت باز',
    closed_count: 'موقعیت‌های بسته',
    open_count: 'موقعیت‌های باز',
    winning_count: 'برد پس از کارمزد',
    losing_count: 'باخت پس از کارمزد',
    breakeven_count: 'سربه‌سر پس از کارمزد',
    win_rate: 'نرخ برد',
    profit_factor: 'ضریب سود',
    expectancy: 'امید ریاضی هر معامله بسته',
    average_hold_seconds: 'میانگین نگهداری بسته (ثانیه)',
    duration_seconds: 'مدت مشاهده‌شده (ثانیه)',
    max_drawdown_fraction: 'بیشترین افت سرمایه',
    max_drawdown_duration_seconds: 'طولانی‌ترین افت (ثانیه)',
    current_drawdown_duration_seconds: 'مدت افت فعلی (ثانیه)',
    open_exposure: 'ارزش ناخالص موقعیت باز با آخرین قیمت',
    exposure_fraction: 'نسبت ارزش موقعیت باز به پرتفوی',
    exposureNote: 'ارزش موقعیت باز = مجموع مقدار × آخرین قیمت ثبت‌شده، برای خرید و فروش.',
    equity: 'ارزش ثبت‌شده پرتفوی',
    drawdown: 'افت ثبت‌شده سرمایه',
    returns: 'بازده ثبت‌شده',
    chartMetricSelector: 'انتخاب شاخص نمودار پرتفوی در موبایل',
    pair: 'جفت‌ارز',
    pairs: 'معاملات به تفکیک جفت‌ارز',
    exits: 'علت خروج موقعیت‌های بسته',
    count: 'تعداد',
    evidence: 'مقادیر رویدادهای مبنای نمودار',
    sequence: 'ترتیب',
    empty: 'موقعیتی ثبت نشده است',
    exitNote: 'شاهد مفقود یا متعارض در دفتر تصمیم‌ها «نامشخص» است و حدس زده نمی‌شود.',
    reasons: {
      unknown: 'نامشخص',
      invalidation: 'ابطال',
      target: 'هدف',
      trend_reversal: 'بازگشت روند',
      portfolio_risk: 'ریسک پرتفوی',
      data_unreliable: 'داده نامعتبر',
      time_expiry: 'انقضای زمان',
      end_of_data: 'پایان داده',
    },
  },
};
